language: node_js
node_js:
  - "9.2.0"
all_branches: true
install: 
  - npm install
test: 
  - npm run test
before_deploy:
    # Set up git user name and tag this commit
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - npm version patch
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    all_branches: true
    file: "package.json"
    skip_cleanup: true
    on:
      repo: Bilchuck/my-ramda
      all_branches: true
  # - provider: npm
  #   email: "bilchuck@me.com"
  #   api_key: $NPM_TOKEN
  #   tag: next