language: node_js
node_js:
  - "iojs"
  - "9.2.0"
before_install:
  - npm install -g npm@5.5.1
install: 
  - npm install
test: 
  - npm run test
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: NPM_TOKEN
  tag: next