language: node_js
node_js:
  - "9.2.0"
all_branches: true
install: 
  - npm install
test: 
  - npm run test
deploy:
  - provider: npm
    skip_cleanup: true
    email: "bilchuck@me.com"
    api_key: $NPM_TOKEN
    on:
      all_branches: true
      condition: "$TRAVIS_COMMIT_MESSAGE == *'Deploying new npm package version'*"