language: node_js
node_js:
  - "9.2.0"
all_branches: true
install: 
  - npm install
test: 
  - npm run test
before_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - npm version patch
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    all_branches: true
    file: "package.json"
    skip_cleanup: true
    on:
      repo: Bilchuck/my-ramda
      branch: master
      condition: "$TRAVIS_COMMIT_MESSAGE == *'Merge'*"
  - provider: npm
    email: "bilchuck@me.com"
    api_key: $NPM_TOKEN
    on:
      repo: Bilchuck/my-ramda
      branch: master
      condition: "$TRAVIS_COMMIT_MESSAGE == *'Merge'*"