language: node_js
node_js:
  - "9.2.0"
install: 
  - npm install
test: 
  - npm run test
before_deploy:
  - npm version patch
  - git push origin HEAD:https://github.com/Bilchuck/my-ramda.git
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: NPM_TOKEN
  tag: next