language: node_js
node_js:
  - "9.2.0"
install: 
  - npm install
test: 
  - npm run test
before_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

  - echo "$GH_TOKEN"
  - echo $GH_TOKEN
  - echo ${GH_TOKEN}


  - git remote add origin https://"$GH_TOKEN"@github.com/Bilchuck/my-ramda.git > /dev/null 2>&1
  - npm version patch
  - git push origin HEAD:master
deploy:
  provider: npm
  email: "bilchuck@me.com"
  api_key: $NPM_TOKEN
  tag: next